nature/apps/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'
urlpatterns = [
	path('', views.index),
	path('home/', views.home, name="home"),
	path('blog/', views.blog, name="blog"),
	path('about/', views.about, name="about"),
	path('contact/', views.contact, name="contact"),
	path('source/', views.source, name="source"),
]

nature/apps/pages_eng/urls.py
from django.urls import path, include
from . import views

app_name = 'pages_eng'
urlpatterns = [
	path('', views.index_eng),
	path('home/', views.home_eng, name="home_eng"),
	path('blog/', views.blog_eng, name="blog_eng"),
	path('about/', views.about_eng, name="about_eng"),
	path('source/', views.source_eng, name="source_eng"),
]

nature/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('eng/', include('pages_eng.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nature/apps/pages/models.py
from django.db import models

# Create your models here.

nature/apps/pages_eng/models.py
from django.db import models

# Create your models here.

nature/apps/pages/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse


def index(request):
	return HttpResponseRedirect("home")

def home(request):
	return render(request, 'rus/home.html')

def blog(request):
	return render(request, 'rus/blog.html')

def about(request):
	return render(request, 'rus/about.html')

def contact(request):
	return render(request, 'contact.html')

def source(request):
	return render(request, 'rus/source.html')

nature/apps/pages_eng/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse


def index_eng(request):
	return HttpResponseRedirect("home_eng")

def home_eng(request):
	return render(request, 'eng/home.html')

def blog_eng(request):
	return render(request, 'eng/blog.html')

def about_eng(request):
	return render(request, 'eng/about.html')

def source_eng(request):
	return render(request, 'eng/source.html')

nature/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact{% endblock %}
{% block content %}
<section class="sub-header">
	<nav>
		<a href="{% url 'pages:home' %}"><img src="{% static 'img/nature.svg' %}"></a>
		<div class="nav-links" id="navLinks">
			<i class="fa fa-times" onclick="hideMenu()"></i>
			<ul>
				<li><a href="{% url 'pages:home' %}">HOME</a></li>
				<li><a href="{% url 'pages:about' %}">ABOUT</a></li>
				<li><a href="{% url 'pages:source' %}">SOURCE</a></li>
				<li><a href="{% url 'pages:blog' %}">BLOG</a></li>
				<li><a href="{% url 'pages:contact' %}">CONTACT</a></li>
			</ul>
		</div>
		<i class="fa fa-bars" onclick="showMenu()"></i>
	</nav>
	<h1>Contact Us</h1>
</section>
<!-- ----- Contact ----- -->

<secction class="location">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d143543.2389387769!2d48.93322039040878!3d55.79561489301278!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x415ead2b7caccd99%3A0x7fcb77b9b5ad8c65!2z0JrQsNC30LDQvdGMLCDQoNC10YHQvy4g0KLQsNGC0LDRgNGB0YLQsNC9!5e0!3m2!1sru!2sru!4v1624974987458!5m2!1sru!2sru" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</secction>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- section -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2433804727494588"
     data-ad-slot="8244274498"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<section class="contact-us">
	<div class="row">
		<div class="contact-col">
			<div>
				<i class="fa fa-home"></i>
				<span>
					<h5>Russia, Kazan, RT</h5>
				</span>
			</div>
			<div>
				<i class="fa fa-envelope-o"></i>
				<span>
					<h5>admiralgeneral2003@gmail.com</h5>
					<p>Email Us Your Query</p>
				</span>
			</div>
		</div>
		<div class="contact-col">
			<form action="" method="post">
				<input type="text" name="name" placeholder="Enter Your Name" required>
				<input type="email" name="email" placeholder="Enter Email Addres" required>
				<input type="text" name="subject" placeholder="Enter Your Subject" required>
				<textarea rows="8" name="message" placeholder="Message" required></textarea>
				<button type="submit" class="hero-btn red-btn">Send Message</button>
			</form>
		</div>
	</div>
</section>

{% endblock %}

nature/templates/eng/about.html
{% extends 'eng/base.html' %}
{% load static %}
{% block title %}About{% endblock %}
{% block content %}
<section class="sub-header">
	<nav>
		<a href="{% url 'pages_eng:home_eng' %}"><img src="{% static 'img/nature.svg' %}"></a>
		<div class="nav-links" id="navLinks">
			<i class="fa fa-times" onclick="hideMenu()"></i>
			<ul>
				<li><a href="{% url 'pages_eng:home_eng' %}">HOME</a></li>
				<li><a href="{% url 'pages_eng:about_eng' %}">ABOUT</a></li>
				<li><a href="{% url 'pages_eng:source_eng' %}">SOURCE</a></li>
				<li><a href="{% url 'pages_eng:blog_eng' %}">BLOG</a></li>
				<li><a href="{% url 'pages:contact' %}">CONTACT</a></li>
				<li><a href="{% url 'pages:about' %}" class="hero-btn red-btn">Rus. Version</a></li>
			</ul>
		</div>
		<i class="fa fa-bars" onclick="showMenu()"></i>
	</nav>
	<h1>About Us</h1>
</section>
<!-- ----- About us Content ----- -->
<section class="about-us">
	<div class="row">
		<div class="about-col">
			<h1>We Make The World A Better Place</h1>
			<p>Our goal is to preserve the natural conditions necessary for the life of people on Earth, for the further development of production and culture. The essence of environmental protection is the establishment of constant dynamic harmony between a developing society and nature, which serves it both as a sphere and a source of life.</p>
			<a href="https://www.greenpeace.org/" class="hero-btn red-btn">GP</a>
			<a href="https://www.worldwildlife.org/" class="hero-btn red-btn">WWF</a>
			<a href="https://www.ifaw.org/uk" class="hero-btn red-btn">IFAW</a>
			<a href="{% url 'pages_eng:source_eng' %}" class="hero-btn red-btn">HELP NOW</a>
		</div>
		<div class="about-col">
			<img src="{% static 'img/about.jpg' %}">
		</div>
	</div>
</section>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- section -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2433804727494588"
     data-ad-slot="8244274498"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
{% endblock %}

nature/templates/eng/blog.html
{% extends 'eng/base.html' %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block content %}
<section class="sub-header">
	<nav>
		<a href="{% url 'pages_eng:home_eng' %}"><img src="{% static 'img/nature.svg' %}"></a>
		<div class="nav-links" id="navLinks">
			<i class="fa fa-times" onclick="hideMenu()"></i>
			<ul>
				<li><a href="{% url 'pages_eng:home_eng' %}">HOME</a></li>
				<li><a href="{% url 'pages_eng:about_eng' %}">ABOUT</a></li>
				<li><a href="{% url 'pages_eng:source_eng' %}">SOURCE</a></li>
				<li><a href="{% url 'pages_eng:blog_eng' %}">BLOG</a></li>
				<li><a href="{% url 'pages:contact' %}">CONTACT</a></li>
				<li><a href="{% url 'pages:blog' %}" class="hero-btn red-btn">Rus. Version</a></li>
			</ul>
		</div>
		<i class="fa fa-bars" onclick="showMenu()"></i>
	</nav>
	<h1>Our Program For Our Future</h1>
</section>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- section -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2433804727494588"
     data-ad-slot="8244274498"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<!-- ----- Blog Page ----- -->
<section class="blog-content">
	<div class="row">
		<div class="blog-left">
			<img src="{% static 'img/success.jpg' %}">
			<h2>Our Way To Success</h2>
			<p>If earlier scientists had to prove that the climate crisis is real, now the inhabitants of the Planet notice with their own eyes climate change: more frequent and destructive hurricanes, ice rains, heat, drought, floods. Moreover, over the past decade, the number of natural hazards that cause significant damage to human health and the economy, according to the Hydrometeorological Center, has more than tripled.</p><br>
			<p>Scientific research has shown that modern warming is due to an increase in the concentration of greenhouse gases in the Earth's atmosphere. It cannot be explained by natural cycles, it is primarily associated with human activities: the burning of fossil fuels - oil, coal and gas - in power plants and in internal combustion engines, the reduction of forest area, including due to fires, the decomposition of organic waste in landfills, agriculture, especially animal husbandry.</p><br>
			<p>The depletion of already developed forests is forcing loggers to go for timber to distant regions of the wild taiga or by hook or by crook to cut down the most valuable forests in densely populated areas.</p><br>
			<p>A forest for economic purposes, with the right approach, can be grown in several decades. But ecosystems of wild forests as a result of industrial felling are destroyed irreversibly - even for their partial restoration it will take centuries, and full restoration is completely impossible.</p><br>
			<p>Rare species of animals perish because of clear-cuttings in the wild valuable forest. To save the reindeer population from extinction, it is necessary to keep several million hectares of forest intact. Improper felling even undermines fish stocks. When the forest is cut down, clay and dead organic matter are washed into the rivers, the settling mud can destroy the eggs of some of the most valuable and rare fish. For example, salmon caviar must be washed with clean and oxygen-rich water, otherwise it dies. You cannot cut down valuable forest in pieces: as a result of a violation of the integrity of the system, a bark beetle can penetrate into the forest and destroy the entire remaining territory.</p><br>
			<p>Fires are a global problem, as they have a huge impact on the planet's climate. Soot from fires reaches the Arctic and settles on the ice, increasing their melting, and during combustion, carbon dioxide is released into the atmosphere - one of the gases responsible for the greenhouse effect and climate change.</p><br>
			<p>Sometimes a fire from a field or forest spreads to residential buildings and other buildings, acrid smoke fills cities and harms the health of people (especially children, allergy sufferers and asthmatics, the elderly suffer).</p>


			<div class="comment-box">
				<h3>Leave a Comment</h3>
				<form class="comment-form">
					<input type="text" placeholder="Enter Name">
					<input type="email" placeholder="Enter Email">
					<textarea rows="5" placeholder="Enter Comment"></textarea>
					<button class="hero-btn red-btn">Post</button>
					<p>Now this does not work, so you can write to the mail: admiralgeneral2003@gmail.com</p>
				</form>
			</div>

		</div>
		<div class="blog-right">
			<h3>Post Categories</h3>
			<div>
				<span>Ecologist</span>
				<span>#1</span>
			</div>
			<div>
				<span>Zoologist</span>
				<span>#2</span>
			</div>
			<div>
				<span>Volunteer</span>
				<span>#3</span>
			</div>
			<div>
				<span>Philanthropist</span>
				<span>#4</span>
			</div>
		</div>
	</div>
</section>
{% endblock %}

nature/templates/eng/home.html
{% extends 'eng/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
<section class="header">
	<nav>
		<a href="{% url 'pages_eng:home_eng' %}"><img src="{% static 'img/nature.svg' %}"></a>
		<div class="nav-links" id="navLinks">
			<i class="fa fa-times" onclick="hideMenu()"></i>
			<ul>
				<li><a href="{% url 'pages_eng:home_eng' %}">HOME</a></li>
				<li><a href="{% url 'pages_eng:about_eng' %}">ABOUT</a></li>
				<li><a href="{% url 'pages_eng:source_eng' %}">SOURCE</a></li>
				<li><a href="{% url 'pages_eng:blog_eng' %}">BLOG</a></li>
				<li><a href="{% url 'pages:contact' %}">CONTACT</a></li>
				<li><a href="{% url 'pages:home' %}" class="hero-btn red-btn">Rus. Version</a></li>
			</ul>
		</div>
		<i class="fa fa-bars" onclick="showMenu()"></i>
	</nav>
<div class="text-box">
	<h1>Nature</h1>
	<p>Save animals and nature from extinction</p>
	<a href="{% url 'pages_eng:source_eng' %}" class="hero-btn">Visit Us to Find Out More</a>
</div>

</section>


<!----- Nature ----->
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- section -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2433804727494588"
     data-ad-slot="8244274498"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<sectio class="course">
	<h1>Problems</h1>
	<p>Our ideals should be at the proper height, not architectural excesses. Can anyone be convinced of this. I honestly tried, but didn't succeed.</p>
	<div class="row">
		<div class="course-col">
			<h3>Air pollution</h3>
			<p>Microscopic pollutants - PM2.5 - are so small that they can penetrate our body's protective barriers, such as mucous membranes, and destroy our lungs, heart and brain.</p>
		</div>
		<div class="course-col">
			<h3>Killing animals</h3>
			<p>It takes 2 liters of oil to get a kilogram of meat. With modern methods of animal husbandry, more poisonous gases are emitted than in all vehicles in the aggregate. Therefore, everyone who is fighting for the environment and convincing us to eat less meat.</p>
		</div>
		<div class="course-col">
			<h3>Destruction of wildlife</h3>
			<p>Between 1980 and 2000, 100 million hectares of rainforest were lost, mainly through clearing forests in South America for grazing and in Southeast Asia for oil palm plantations.</p>
		</div>
	</div>
</sectio>
<!-- ----- Worlds ----- -->
<section class="campus">
	<h1>Environment</h1>
	<p>"Gibraltar" I think of hundreds of unknown daredevils who die every year trying to get to this rock. For those who live in Africa, Gibraltar is a symbol of new life. Is it possible to forbid dreams of a better life, because this is what people have been striving for from time immemorial.</p>
	<div class="row">
		<div class="campus-col">
			<img src="{% static 'img/nature.jpg' %}">
			<div class="layer">
				<h3>Nature</h3>
			</div>
		</div>
		<div class="campus-col">
			<img src="{% static 'img/panda.jpg' %}">
			<div class="layer">
				<h3>Animal</h3>
			</div>
		</div>
		<div class="campus-col">
			<img src="{% static 'img/cityRain.jpg' %}">
			<div class="layer">
				<h3>People</h3>
			</div>
		</div>
	</div>
</section>
<!-- ----- Facilities ----- -->
<section class="facilities">
	<h1>Out on a Limb</h1>
	<p>We are so powerful now that we can empty the sea like this bath. We often receive warnings about an impending catastrophe, but we are not able to imagine when it already happened and it was on the Aral Sea.</p>
	<div class="row">
		<div class="facilities-col">
			<img src="{% static 'img/landMountain.jpg' %}">
			<h3>Nature</h3>
			<p>Who would have thought that this could be encountered here in Nepal. In the highest mountains, where the air would seem to be clean. Scientists have proven that at the top of the Himalayan ridge, the air is as polluted as in our cities. Due to the currents of atmospheric air, which is trapped by the mountains.</p>
		</div>
		<div class="facilities-col">
			<img src="{% static 'img/oceanWhale.jpg' %}">
			<h3>Animas</h3>
			<p>Once oil gave whales a chance, they were hunted in the early 19th century. Their fat was burned in oil lamps, and machine parts were lubricated with it. When it became scarce, it was gradually replaced by oil, for the whales it became a salvation. A paradox or an illusion, for the hunt has begun again.</p>
		</div>
		<div class="facilities-col">
			<img src="{% static 'img/china.jpg' %}">
			<h3>People</h3>
			<p>Intensive development of agriculture in the 60s in India. Saved from hunger, but at the same time depleted, subsoil waters. When the wells dry up here, they begin to dig ponds when the rainy season comes into play. We in our world simply forgot how important water is.</p>
		</div>
	</div>
</section>
<!-- ----- TestiMonials ----- -->

<section class="testimonials">
	<h1>What Our Student Says</h1>
	<p>Yes, indeed, environmentalists are not born, they become. Our land is even more beautiful than one can imagine.</p>
	<div class="testimonials-col">
		<img src="{% static 'img/girl.jpg' %}">
		<div>
			<p>I gained a lot, learned a lot. Now I want you to familiarize yourself with this.</p>
			<h3>Aiony Haust</h3>
			<i class="fa fa-star"></i>
			<i class="fa fa-star"></i>
			<i class="fa fa-star"></i>
			<i class="fa fa-star"></i>
			<i class="fa fa-star-half-o"></i>
		</div>
	</div>
	<div class="testimonials-col">
		<img src="{% static 'img/boy.jpg' %}">
		<div>
			<p>Thanks to this site, I got acquainted with all the beauty of the world that surrounds me.</p>
			<h3>Nicolas Horn</h3>
			<i class="fa fa-star"></i>
			<i class="fa fa-star"></i>
			<i class="fa fa-star"></i>
			<i class="fa fa-star"></i>
			<i class="fa fa-star-o"></i>
		</div>
	</div>
</section>
<!-- ----- Call To Action ----- -->
<section class="cta">
	<h1>Contact Us To Make <br>The World a Better Place</h1>
	<a href="{% url 'pages:contact' %}" class="hero-btn">CONTACT US</a>
</section>
{% endblock %}

nature/templates/eng/source.html
{% extends 'eng/base.html' %}
{% load static %}
{% block title %}Source{% endblock %}
{% block content %}
<section class="sub-header">
	<nav>
		<a href="{% url 'pages_eng:home_eng' %}"><img src="{% static 'img/nature.svg' %}"></a>
		<div class="nav-links" id="navLinks">
			<i class="fa fa-times" onclick="hideMenu()"></i>
			<ul>
				<li><a href="{% url 'pages_eng:home_eng' %}">HOME</a></li>
				<li><a href="{% url 'pages_eng:about_eng' %}">ABOUT</a></li>
				<li><a href="{% url 'pages_eng:source_eng' %}">SOURCE</a></li>
				<li><a href="{% url 'pages_eng:blog_eng' %}">BLOG</a></li>
				<li><a href="{% url 'pages:contact' %}">CONTACT</a></li>
				<li><a href="{% url 'pages:source' %}" class="hero-btn red-btn">Rus. Version</a></li>
			</ul>
		</div>
		<i class="fa fa-bars" onclick="showMenu()"></i>
	</nav>
	<h1>All Source</h1>
</section>
<!----- Source ----->
<sectio class="course">
	<h1>Problems</h1>
	<p>Difficulties make strong people even stronger, and, oddly enough, more cheerful, and the weak become evil, and this destroys them.</p>
	<div class="row">
		<div class="course-col">
			<h3>Air pollution</h3>
			<p>Air pollution levels remain dangerously high in many parts of the world. According to new data from the World Health Organization (WHO), 9 out of 10 people breathe air with a high concentration of pollutants. Alarmingly, updated estimates show that 7 million lives are lost from ambient (atmospheric) and indoor air pollution each year.</p>
		</div>
		<div class="course-col">
			<h3>Killing animals</h3>
			<p>There is a lot of fish in the coastal waters of Mauritania, so there are many fishing boats here. They suffer from fierce competition due to the fact that fish stocks have drastically decreased. 96% of the world's fishermen catch in the most primitive way, but present only 30% of the catch.</p>
		</div>
		<div class="course-col">
			<h3>Destruction of wildlife</h3>
			<p>One liter of engine oil can contaminate more than 1 million liters of drinking water. Many people may think that 1 million liters of clean water is really a lot, but that is how much water only 12-13 people drink per year.</p>
		</div>
	</div>
</sectio>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- section -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2433804727494588"
     data-ad-slot="8244274498"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<!-- ----- Facilities ----- -->
<section class="facilities">
	<h1>Out on a Limb</h1>
	<p>We have only recently begun to understand how important these forests are to us. Although they are so far from us. After all, they help maintain the overall balance, where everything has its place and on which we are completely dependent. It is no longer possible to save in one place and plunder in another. For everything is interconnected.</p>
	<div class="row">
		<div class="home-left">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/jqxENMKaeCU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		</div>
		<div class="home-right">
			<h3>HOME</h3>
			<p>It's not a secret for anyone that during its existence, man has exhausted a huge amount of natural resources. But perhaps not everyone knows that humanity is moving towards a global catastrophe much faster than we thought. According to the recently released documentary "HOME" ("HOME" in the original version), in 10 years the population of the planet Earth may face a global cataclysm that will affect everyone without exception.<br><br>The film was directed by Jan Arthus Bertrand and produced by Luc Besson. Many countries took part in the creation of the picture. The main sponsor was the PPR (Pinault-Printemps-Redoute) group, which includes many companies from the luxury, automotive and cultural industries. For example, it includes the Gucci Group, the world's second largest luxury operator. In this regard, there were rumors that the film is an act of greenwashing (I don't know if there is an equivalent in Russian, but this is when large companies spend a lot of money to convince everyone that they are environmentally responsible, although they actually spend more money on "false advertising" than they actually invest in greener production paths).<br><br>In any case, greenwashing or not, I think that the film is worth watching for everyone and that it raises really serious and important questions that should be pondered by all of us, and above all by the governments of all countries. After all, when it comes to the future of the planet, it doesn't matter who paid for what, but it is important that all countries unite so that our and future generations can live on planet Earth.</p>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="human-col">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/vdb4XGVTHkE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
			<div class="human-layer">
				<h3>HUMAN Vol. 1</h3>
			</div>
		</div>
		<div class="human-col">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/ShttAt5xtto" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
			<div class="human-layer">
				<h3>HUMAN Vol. 2</h3>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="human">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/w0653vsLSqE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
			<div class="human-layer">
				<h3>HUMAN Vol.3</h3>
			</div>
		</div>
		<div class="human-right">
			<h3>HUMAN</h3>
			<p>What makes us human? The ability to love and fight? What are we laughing at? Crying? Curiosity? Desire for discovery?<br><br>All these questions concern the producer and artist Yann Artus-Bertrand, who has been collecting stories from the lives of different people for three years. He has already collected stories about the lives of 2,000 women and men from 60 countries around the world. Yann works with a team of dedicated translators, journalists and cameramen. With their help, he managed to get frank and deeply emotional conversations on topics that unite us all: the fight against poverty, war, homophobia and the future of our planet, and, of course, all this is connected with personal moments of love and happiness.<br>Watch 3 volumes of our film and think with us What makes us human. #WhatMakesUsHUMAN</p>
		</div>
	</div>
</section>
{% endblock %}

nature/templates/rus/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock %}
{% block content %}
<section class="sub-header">
	<nav>
		<a href="{% url 'pages:home' %}"><img src="{% static 'img/nature.svg' %}"></a>
		<div class="nav-links" id="navLinks">
			<i class="fa fa-times" onclick="hideMenu()"></i>
			<ul>
				<li><a href="{% url 'pages:home' %}">HOME</a></li>
				<li><a href="{% url 'pages:about' %}">ABOUT</a></li>
				<li><a href="{% url 'pages:source' %}">SOURCE</a></li>
				<li><a href="{% url 'pages:blog' %}">BLOG</a></li>
				<li><a href="{% url 'pages:contact' %}">CONTACT</a></li>
			</ul>
		</div>
		<i class="fa fa-bars" onclick="showMenu()"></i>
	</nav>
	<h1>About Us</h1>
</section>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- section -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2433804727494588"
     data-ad-slot="8244274498"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<!-- ----- About us Content ----- -->
<section class="about-us">
	<div class="row">
		<div class="about-col">
			<h1>We Make The World A Better Place</h1>
			<p>Наша цель заключается в сохранении природных условий, необходимых для жизни людей на Земле, для дальнейшего развития производства и культуры. Сущность охраны окружающей природной среды состоит в установлении постоянной динамической гармонии между развивающимся обществом и природой, служащей ему одновременно и сферой, и источником жизни.</p>
			<a href="https://greenpeace.ru/" class="hero-btn red-btn">GP</a>
			<a href="https://wwf.ru/" class="hero-btn red-btn">WWF</a>
			<a href="https://www.ifaw.org/uk" class="hero-btn red-btn">IFAW</a>
			<a href="{% url 'pages:source' %}" class="hero-btn red-btn">HELP NOW</a>
		</div>
		<div class="about-col">
			<img src="{% static 'img/about.jpg' %}">
		</div>
	</div>
</section>
{% endblock %}